### ISSUE TITLE
The door in Gammas tower leading to the commons has a bugged zone transfer

### ISSUE THREAD

**Issue by Phill030** [Revive101/Imlight#142]
### Description of the problem

The door in Gammas tower leading to the commons has a bugged zone transfer

### Reproduction steps

Going into Gammas tower from either location and upon attempting to exit to the commons, no attempt is made to try and go to the commons. Just showing the splash screen for a zone transfer while you can move your character around still.

### Expected behaviour

Upon hitting the zone transfer of the door connect to the zone server in the commons.

### Additional context

The character is still moving around in gammas tower, in the logs of power shell it does not attempt a connection to the zone server at all. Is a chance not a guarantee. Will upload a video soon.

> Moved Bugreport from [B](@BV2O) @ 08/08/2023 10:29 PM

**Comment by gmrush** [comment]
QA has since added this zone transfer.

**Comment by Jooty** [comment]
This bug report is a little undescriptive, but it's talking about the seemingly random zone transfer hang that happens when a player moves too fast through transfers. However it is difficult to fix this one because it is not producible locally. It seems the latency of an actual server is somewhat responsible.

I'm going to re-open this to see if it happens for QA again.

**Comment by PokemonHacker1337** [comment]
I was able to intentionally reproduce this by going to Gamma's Tower from the commons and keep going through the same door repeatedly, so I can confirm that it does still happen.

**Comment by Jooty** [comment]
This may have been fixed with `feature/tower-shield`. I simply cannot reproduce this bug on my local machine.

**Comment by ghost** [comment]
i got the bug once, but now i can't reproduce it again. i think it might be related to the character being able to move around while the loading screen is up

**Comment by BV2O** [comment]
I can confirm the bug still happens. 
https://github.com/Revive101/Imlight/assets/150472453/d300c05f-6510-4010-b403-49c7a369f93e
[WizardClient.log](https://github.com/Revive101/imlight-issues/files/13544538/WizardClient.log)
The odds of encountering it seem to be lower than the first time it was encountered as it took around 30 minutes to appear, while the first encounter with it only took a few minutes between attempts to happen multiple times.

**Comment by Jooty** [comment]
Dropping the priority on this one. If it's only happening on one transfer, and takes 30 minutes to even achieve, it'll probably go on backlog. That being said, if anyone can manage to get this to happen on any other transfer, please update this issue.

**Comment by BV2O** [comment]
So this clip its hard to tell with the other sound effects, but I'm hearing footsteps so will see if others do. The log is showing a similar pattern to what happened with gamma tower. In this I wasn't recording yet, but I had just logged in and used the teleport command to go check if a zone transfer was fixed. So this happened in under a minute I started in 5Room3_3 and was teleporting to 6Room.
[WizardClient (4).log](https://github.com/Revive101/imlight-issues/files/13638486/WizardClient.4.log)

https://github.com/Revive101/Imlight/assets/150472453/a699854a-0d8d-43dd-878c-c706a54de4f2

**Comment by Phill030** [comment]
@PokemonHacker1337 / @BV2O can you check if this is still the case?

**Comment by BV2O** [comment]
@Phill030 Had it happen twice yesterday so still happening.
Edit:I should mention my latency/connection with the server might be why I seen it so often, as no one else seems to have it happen so frequently as I do.

**Comment by PokemonHacker1337** [comment]
I've never had this happen recently, maybe it could be possible to invoke with Cheat Engine's speedhacking or something.
